### ISSUE TITLE
How about cleaning up compilation and running process?

### ISSUE THREAD

**Issue by tmvkrpxl0** [ahgamut/rust-ape-example#2]
In the provided README, step 2 highlights this build command:
```sh
cargo +nightly build -Zbuild-std=libc,panic_abort,std -Zbuild-std-features=""  --target=./x86_64-unknown-linux-cosmo.json
```
But it is possible for a project to have this all configurations for itself so that simple `cargo build` can do all this

./rust-toolchain.toml:
```toml
[toolchain]
channel = "nightly" # this specific project will use nightly as default
```

./.cargo/config.toml:
```toml
[build]
target = "x86_64-unknown-linux-cosmo.json" # changes default target

[unstable]
build-std-features = [""]
build-std = ["libc", "panic_abort", "std"]

[profile.dev]
panic = "abort"
opt-level = "s"

[profile.release]
panic = "abort"
opt-level = "s"
```
Although I  currently can't get it to working so I can't test these new configurations, these should do the same.
Additionally, `config.toml` can also specify runner. I haven't dig deep into cosmo but I assume it's possible to skip `objcopy` and run compiled output straight up with `cargo run`

**Comment by ahgamut** [comment]
Storing the build configuration in a file makes it simpler. Thanks!
Cosmopolitan Libc has improved a lot since I made this repo, I'll check the build system soon.

**Comment by ahgamut** [comment]
Updated the build steps. You will need to download the Cosmopolitan Libc repo and setup the toolchain, I would recommend installing `qemu-aarch64` as well.

If everything is setup correctly, you can run

```bash
cargo +nightly build --target=x86_64-unknown-linux-cosmo.json
cargo +nightly build --target=aarch64-unknown-linux-cosmo.json
```

to get the debug executables for each arch, and then run `apelink.com` to combine them. (@jart may have some additional suggestions.)

**Comment by tmvkrpxl0** [comment]
I'm currently unsure of how to automatically combine multiple archs with cargo using apelink but without compiling for aarch64, I got it working just by `cargo run --bin hello`

**Comment by ahgamut** [comment]
```bash
cargo run --bin hello
# equivalently
./target/x86_64-unknown-linux-cosmo/debug/hello.com.dbg # is an ELF x86_64 executable 
./target/aarch64-unknown-linux-cosmo/debug/hello.com.dbg # is an ELF aarch64 executable
```

cargo doesn't automatically combine multiple archs (yet?), that's a feature from Cosmopolitan Libc. 

You can create a fat executable by using `apelink.com` to combine the debug executables from each arch, as below:

```bash

MODE=
MODE_AARCH64=aarch64
APELINK=$COSMO/o/tool/build/apelink.com
apelinkpls () {
    OUTPUT="$1"
    OUTPUT_X86_64="$2"
    OUTPUT_AARCH64="$3"
    "$APELINK" -l "$COSMO/o/$MODE/ape/ape.elf" \
        -l "$COSMO/o/$MODE_AARCH64/ape/ape.elf" \
        -M "$COSMO/ape/ape-m1.c" \
        -o "$OUTPUT" \
        "$OUTPUT_X86_64" \
        "$OUTPUT_AARCH64"
}

apelinkpls ./hello.com\
    ./target/x86_64-unknown-linux-cosmo/debug/hello.com.dbg\
    ./target/aarch64-unknown-linux-cosmo/debug/hello.com.dbg
    
./hello.com # Actually Portable Executable
```

**Comment by tmvkrpxl0** [comment]
Yeah, I mean I was curious to see if it can be done in one liner but I guess it's not without making custom tool for cargo
