### ISSUE TITLE
 system constants in Rust are decided at compile time

### ISSUE THREAD

**Issue by Jules-Bertholet** [ahgamut/rust-ape-example#3]
In Cosmopolitan, the values of many system constants (syscalls, errno, etc) are [different for different systems](https://github.com/jart/cosmopolitan/blob/6ca5ab468033c899f18002e959d6d86a36cea9bd/libc/sysv/consts.sh) and only available at runtime. The Rust target definition in this repo specifies [`"os":"linux", "env": "musl"`](https://github.com/ahgamut/rust-ape-example/blob/f81a13d73d0c5515bc65b20d3b90bc983d96d4e9/x86_64-unknown-linux-cosmo.json#L7-L8), which is what the `libc` crate uses (via `#[cfg(..)]`) to determine what it thinks the values of these constants is. Naturally, these will match only on Linux platforms, so `libc`'s dependents, including `std`, will be broken everywhere else.

**Comment by ahgamut** [comment]
Thanks for the note! For my reference, can you link to the part of the libc crate source that actually decides the system constants? I'd like to know that the fat binary would work on x86-64 linux and aarch64 linux, because those are the `env`s that are fixed by the config file.

**Comment by Jules-Bertholet** [comment]
They are split across many different files, each platform has its own. You can search for them individually: `pub const EINVAL`/`SIGABRT`/`MAP_INHERIT`/…

**Comment by ahgamut** [comment]
I just want to link to one of them so I can say the APE is for x86-64 linux and aarch64-linux. 

Is it possible for the system constants to be `extern` values in Rust? I know the C standard doesn't allow `extern` constants within switch-cases, which is where the errnos are frequently used, so I wrote a small `gcc` patch to allow that behavior in C.

**Comment by ahgamut** [comment]
I shall link to https://github.com/search?q=repo%3Arust-lang%2Flibc%20EINVAL&type=code showing that Rust constants are decided at compile-time.

**Comment by ahgamut** [comment]
Updated the README. Thanks for the heads up!

**Comment by Jules-Bertholet** [comment]
> Is it possible for the system constants to be extern values in Rust? I know the C standard doesn't allow extern constants within switch-cases, which is where the errnos are frequently used, so I wrote a small gcc patch to allow that behavior in C.

`std` uses these `const`ants as `match` patterns a lot; Rust does not allow `static`s to appear in such patterns, so `std` won't compile if you replace the `const`s with `extern { static ... }`s. A year ago, I submitted [a Rust RFC](https://github.com/rust-lang/rfcs/pull/3305) that would have fixed this, but [it was rejected](https://github.com/rust-lang/rfcs/pull/3305#issuecomment-1238524298).

Even if you fix that, IIRC some widely used crates outside `std`, like `nix`, use some of these constants as `enum` discriminant values; that's not something that could likely ever be supported with `static`s.
